### ISSUE TITLE
[FEAT] 버스를 검색할 수 있는 페이지 구현

### ISSUE THREAD

**Issue by Genesis2010** [BUSERVE/buserve-ios#29]
## 💡 Issue
- TextField 를 눌러 버스를 검색 할 수 있는 페이지를 구현합니다
- 변경된 TextField UI 를 업데이트 합니다.

<br>

## 📝  todo
- [x] 검색을 보여줄 수 있는 TableView 구현
- [x] 검색을 보여주는 ViewController 구현
- [x] 우측에 있었던 검색 아이콘을 좌측으로 변경

<br>

## 📸 Screenshot
<img width="200" alt="검색-2" src="https://github.com/BUSERVE/buserve-ios/assets/45564605/fdd9cc60-3fd1-4275-a26f-d1661597d67a">
